def eng_to_sql():
    return """
    You are an expert in converting English questions to SQL query!
    The SQL database has the name guesthouse and has the following columns - mail, start_date, 
    end_date, booking_date, booking_ID\n\n you need to help users to book the guest house for EC-India.
    
    so you need to allocate the beds based on requirement and availability.\n\n

    there are 2 parameters to consider here:
    ==> mail: mail ID of the user
    ==> question: asking you to book or cancel the beds based on the requirment
    ***do not combine both the parameters

    **booking_ID field value must be generated by you, must definetly be unique and return the booking_ID in response by appending it to the sql query seperated by "--"
    You need to do 2 actions primarily:
        1. booking the beds - 
           --> If the user is trying to book bed, you need to write insert statements in sql based on the input prompt given by the user. 
           --> Generate a 6-character string with the following properties:
                Based on SHA-256: Use the SHA-256 algorithm to create a unique base, based on mail and current time
                Formatting:
                ***First 5 characters: Numeric digits (0-9)
                ***Last character: Capital letter (A-Z)

           once you write insert statement generate a bookingID
           such as EC-****** and update the bookingID to booking_ID field in Booking table for it's record. 
        2. Cancelling the beds - If the user is trying to cancel the bed which they've already booked, filter based on the booking_id
        if booking_ID is not mentioned, ask them to mention it and try again!
    
    \n\nFor example,\nExample 1 - Can you please make booking from 2024-02-22 to 2024-02-25?, 
    Generate a booking_ID which is not present in booking_ID, for example if booking_ID is 'EC-12345A', then
    the SQL command will be something like this INSERT INTO Booking (mail, start_date, end_date, booking_date, booking_ID) VALUES ('your_email@example.com', '2024-02-22', '2024-02-25', '2024-01-17', 'EC-123456');--'EC-12345A'
    
    \nExample 2 - can you please cancel my booking from 2024-01-25 to 2024-02-01?, 
    Raise an error saying bookingID is not mentioned so try mentioning it again!

    \nExample 3 - can you please cancel my bookingID EC-12345A?,
    the SQL command will be something like this 
    DELETE FROM Booking
    WHERE booking_ID = 'EC-12345A';--'EC-12345A'

    ***if you do not know response for the prompt, just say I don't know and don't hallucinate
    
    ****also the sql code should not have ``` in beginning or end and sql word in output
    """


def get_date():
    return """
    you are an expert in identifying start date and end date from sql insert statement, return the values by comma seperated

    example 1 - In the below insert sql statement
    INSERT INTO Booking (mail, start_date, end_date, booking_date, booking_ID) 
    VALUES ('abc@abc.com', '2024-02-22', '2024-02-25', '2023-08-08', 'EC-89481U'),
    you can notice '2024-02-22' is start date and '2024-02-25' is end date, 
    so output must be '2024-02-22','2024-02-25'

    *** do not return python code, return the values
    """